### ISSUE TITLE
Publish to JsDelivr or Unpkg

### ISSUE THREAD

**Issue by tlvenn** [OlegIlyenko/graphiql-workspace#1]
Now that the project is properly published to npm, it should be trivial to add it to jsdelivr so it can be automatically managed by their bot.

@OlegIlyenko do you want to me to take care of that ?

**Comment by tlvenn** [comment]
We need to produce a single js / css file that is pushed to npm before we can setup jsdelivr

**Comment by tlvenn** [comment]
Everything is ready there: https://github.com/tlvenn/jsdelivr/tree/patch-1/files/graphiql-workspace

TODO:
- [ ] Review and merge #2 
- [ ] Fix #3 
- [ ] Publish updated version to npm

**Comment by tlvenn** [comment]
Hi @OlegIlyenko,

Once those 2 PRs are merged, can you please publish a new version to npm then I will coordinate with JsDelivr to update the version they have.

Thanks !

**Comment by tlvenn** [comment]
@OlegIlyenko any update ? We really need to publish a new version asap plz. Thanks in advance !

**Comment by OlegIlyenko** [comment]
Sorry that it took me so long. **v1.0.1** is now published:

https://github.com/OlegIlyenko/graphiql-workspace/releases/tag/v1.0.1

You can also access files with unpkg:

https://unpkg.com/graphiql-workspace@1.0.1/graphiql-workspace.css
https://unpkg.com/graphiql-workspace@1.0.1/graphiql-workspace.js
https://unpkg.com/graphiql-workspace@1.0.1/graphiql-workspace.min.js

**Comment by tlvenn** [comment]
I did not know about unpkg, probably a better option for npm packages given there is nothing to do. Will close this issue then.

Thanks for the update @OlegIlyenko.
