### ISSUE TITLE
Header edit/delete buttons are inaccessible for long headers

### ISSUE THREAD

**Issue by robertpeacock22** [OlegIlyenko/graphiql-workspace#10]
When you add a very long header such as an auth token, the masked token does not wrap. As a result it pushes the edit and delete buttons far off the right side of the page.

In Firefox I can access the buttons by zooming out extremely far.
![screen shot 2016-12-16 at 11 26 11 am](https://cloud.githubusercontent.com/assets/608951/21270840/5d6a0ede-c386-11e6-95db-f2a7aedf3672.png)

In Chrome I'm not even able to zoom out far enough to bring the buttons on screen.

Expected:
Either the position of the buttons should be moved (e.g. just under the header name), or the masked token should wrap lines, leaving space at the right for the buttons.

**Comment by OlegIlyenko** [comment]
This issue was fixed a while ago. I assume you are using outdated version. Now headers are truncated like this:

![truncated-gheaders](https://cloud.githubusercontent.com/assets/156569/21276106/3bfaabc4-c3d0-11e6-89b4-c50f24c32c56.png)

**Comment by robertpeacock22** [comment]
@OlegIlyenko Thanks for pointing this out! The version of GraphiQL we have appears to be coming from Absinthe-Plug, which in turn appears to be coming from [this graphql-toolbox](https://github.com/jsdelivr/jsdelivr/tree/master/files/graphql-toolbox). I'm not sure why the version number (1.0.1) is so disparate from [the one in your graphql-toolbox](https://github.com/OlegIlyenko/graphql-toolbox/blob/master/package.json) (0.1.0).

At any rate, this is not actually an issue with `graphiql-workspace`. I'm closing this issue, but do you happen to have any insight into why this might be the case?
