### ISSUE TITLE
Subscription Support?

### ISSUE THREAD

**Issue by bruce** [OlegIlyenko/graphiql-workspace#21]
Any plans to add subscription support, eg, supporting a pluggable fetcher that would work with https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher? It's relatively painless to get it working with vanilla GraphiQL.

**Comment by tlvenn** [comment]
@OlegIlyenko any update on this ? Thank !

**Comment by tlvenn** [comment]
Addressed with #22

**Comment by kachkaev** [comment]
#22 is now merged! Many thanks @tlvenn!

**Comment by bruce** [comment]
Closing this. Thanks, everyone :-)
