### ISSUE TITLE
Can't resolve 'graphiql-subscriptions-fetcher'

### ISSUE THREAD

**Issue by kachkaev** [OlegIlyenko/graphiql-workspace#24]
I'm trying to build [graphiql-workspace-app](https://gitlab.com/kachkaev/graphiql-workspace-app) after updating to 1.0.5 and am getting this error:

```
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'graphiql-subscriptions-fetcher' in '/path/to/graphiql-workspace-app/node_modules/graphiql-workspace/dist'
```

@tlvenn could this be related to your [changes in package.json](https://github.com/OlegIlyenko/graphiql-workspace/blame/master/package.json#L27-L29)?

__UPD:__ See [CI build logs](https://gitlab.com/kachkaev/graphiql-workspace-app/-/jobs/34422226).

**Comment by tlvenn** [comment]
@kachkaev the issue with `graphiql-subscriptions-fetcher` is that it does not produce the expected main entrypoint `index.js` but `fetcher.js`. Depending on your packager, you will have to help it out figuring the correct entrypoint. 

In the case of Browserify, this can be done with a `browser` entry in the package.json as you have seen. Create React App is using Webpack so you will have to check how this is done in Webpack.

**Comment by kachkaev** [comment]
I see. There is an issue for that: https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher/issues/4

I'm using [create-react-app](https://github.com/facebookincubator/create-react-app), which is one of the most popular boilerplates today and I don't think it would allow a config you are mentioning. How about this workaround in this repo's code ([suggested](https://github.com/apollographql/GraphiQL-Subscriptions-Fetcher/issues/4#issuecomment-325193565) by @twelve17)?

```js
import { graphQLFetcher } from 'graphiql-subscriptions-fetcher/dist/fetcher'; 
```

**Comment by tlvenn** [comment]
Sure that would totally work. Would you mind create a PR to address the issue ? Thanks in advance.
