### ISSUE TITLE
observer is not defined

### ISSUE THREAD

**Issue by kachkaev** [OlegIlyenko/graphiql-workspace#30]
Hi Oleg,

Looks like the subscriptions are not working in the latest version. [GraphiQLSubscriptionsFetcher.js](https://github.com/OlegIlyenko/graphiql-workspace/blob/62589799ee30f170b42bec54167f3401ac8fb9f7/src/GraphiQLSubscriptionsFetcher.js) refers to a variable called `observer`, but it is not defined. Getting an exception when trying to subscribe to something.

![screenshot from 2017-11-03 16-52-54](https://user-images.githubusercontent.com/608862/32385917-7db0c906-c0b7-11e7-9db7-7a255a944a17.png)

---

I'm also wondering if sending subscriptions could be disabled when the ws url is not defined. I forgot to define it today and sent a subscription, but this resulted an odd error, because the query was sent to the HTTP server:

![screenshot from 2017-11-03 16-54-30](https://user-images.githubusercontent.com/608862/32386055-eacafe80-c0b7-11e7-8200-658a5853b721.png)

Apollo tried resolving a subscription when there's no event, so the payload was undefined.

**Comment by tlvenn** [comment]
Yep @OlegIlyenko broke it with this commit: 62589799ee30f170b42bec54167f3401ac8fb9f7
The dependency on `subscription-transport-ws` should target 0.8.x, they have deprecated the API the fetcher is using in 0.9.x

I will submit a PR shortly to fix this.

**Comment by OlegIlyenko** [comment]
Just published v1.1.4 Sorry for breaking the deps 😰  Thanks again got fixing it, @tlvenn!

**Comment by kachkaev** [comment]
Thanks Oleg! Updating to `1.4.4` worked for me in my [`create-react-app` instance](https://gitlab.com/kachkaev/graphiql-workspace-app), although I had to switch to `yarn` in order to avoid a duplicate `graphql` dependency (versions `0.11.*` and `0.10.*`). @tlvenn many thanks for introducing the `"resolutions"` section in `package.json` – otherwise I'd fiddle with duplicate deps forever 😃
