### ISSUE TITLE
Consider changing Request.credentials from same-origin to include

### ISSUE THREAD

**Issue by jcbpl** [OlegIlyenko/graphiql-workspace#38]
I'm interested in deploying graphiql-workspace so that it could be used to call multiple authenticated graphql endpoints that run on subdomains of my company's TLD. Currently, the implementation of `fallbackFetcher` precludes this because it calls `fetch` with `credentials: 'same-origin'` instead of `credentials: 'include'`: 

https://github.com/OlegIlyenko/graphiql-workspace/blob/967c3d524960c42867471f25127df38770f0a4f4/src/GraphiQLTab.jsx#L535

Would there be any objection to changing `same-origin` to `include`? (FWIW, that's what the reference example in the graphiql repo [does](https://github.com/graphql/graphiql/blob/master/example/index.html#L119).)

Alternatively, if the use of `same-origin` is deliberate, would it be possible to make it a configuration option?

Thanks!

**Comment by OlegIlyenko** [comment]
I'm not an expert on CORS, but I think `include` has it's own set of issues: https://github.com/OlegIlyenko/graphiql-workspace/pull/27 (the original PR that chnages it to `same-origin`).

I don't mind parametrizing it though. Would you like to make a PR?

**Comment by jcbpl** [comment]
Ah, got it. Yep, I'll open a PR.
