### ISSUE TITLE
Missing react-bootstrap css ?

### ISSUE THREAD

**Issue by tlvenn** [OlegIlyenko/graphiql-workspace#4]
In your example, you are requiring 2 css files:

```
import 'graphiql-workspace/graphiql-workspace.css'
import 'graphiql/graphiql.css'
```

Since `graphiql-workspace.css` is a standalone css file now, shouldnt we need to import `react-bootstrap.css` as well ?

**Comment by OlegIlyenko** [comment]
Yeah we need it as well (and I probably should mention it in README). The thing about it is that it should be handled externally as far as i understood. In graphql-toolsbox, for instance, I add it with `bootstrap-loader` in webpack config. But I'm not very experienced in this area, so I would appreciate any suggestion in this area.

On the other hand, in past people has issue with bundled bootstrap css (the fornts, for instance, were not properly linked), so maybe it's indeed better to handle bootstrap in the final app directly.

**Comment by tlvenn** [comment]
Given you have added a comment in the Readme (https://github.com/OlegIlyenko/graphiql-workspace/commit/64bc52b5b7883e5e2324f3009212f30bfb42b5d3) we can close this issue.

For reference, in my template file, I pull the bootstrap css from:
> https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css
