### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by pbojinov** [OlegIlyenko/graphiql-workspace#43]
The link to **graphql-toolbox** in the README.md takes you to a broken page that looks like spam 

> You still will need to add bootstrap CSS in you final application. For instance, you can use bootstrap-loader in webpack config. For an example application, that uses graphiql-workspace, check out graphql-toolbox

Link in question: http://toolbox.sangria-graphql.org/graphiql

**Comment by kachkaev** [comment]
Sadly, the link in this repo cannot be changed 😔

- https://github.com/sangria-graphql/sangria/issues/445
- https://www.reddit.com/r/scala/comments/bn1ia9/sangria_creator_oleg_ilyenko_has_passed_away/
- https://github.com/sangria-graphql/sangria-graphql.github.io/issues/74

**Comment by pbojinov** [comment]
I'm really sorry to hear that. Thank you for letting me know @kachkaev
