### ISSUE TITLE
Making Default Headers configurable

### ISSUE THREAD

**Issue by thisismana** [OlegIlyenko/graphiql-workspace#6]
I was trying to upgrade to this latest version, but the fact that the source code is now in an external npm repo restricts the configuration by using the `AppConfig` class.

Unfortunately, I have little knowledge of JS and React, but it seems that there is only a subset that can be configured. This works on my project:

```
module.exports.setupGraphiQLWorkspace = function (bootstrapOptions = {
    defaultUrl: 'https://graphql.up.welt.de/graphql',
    defaultQuery: '{ search( section: "/wissenschaft/" ) {\n    headline\n  }\n}',
}) {this.bootstrapOptions = bootstrapOptions;
    const config = new AppConfig("graphiql", bootstrapOptions);
    ReactDOM.render(<GraphiQLWorkspace config={config}/>, document.getElementById('graphiql-workspace'));
};
```

How would I modify the `defaultHeaders`? I need to replace the default `Authorization` header with an `X-Api-Key` header.

**Comment by OlegIlyenko** [comment]
Indeed only a small subset of properties are customizable:

https://github.com/OlegIlyenko/graphiql-workspace/blob/5b5b88e6eb6079c2c313b3e7862cb454480a823f/src/config.js#L79-L83

If you would like to customize more things, I would appreciate if you can make a PR and add more `AppConfig` options (at least for default headers). Would be happy to merge it :)
