### ISSUE TITLE
Default variables => {}

### ISSUE THREAD

**Issue by kachkaev** [OlegIlyenko/graphiql-workspace#7]
Hi Oleg!

At the moment query variables are empty by default in the interface. This causes an an error in every new tab that's trying to hit an apollo graphql server. Looks like it's because that server expects variables to be either not defined at all or defined as as something serializable. Now it's an empty string:

![screen shot 2016-12-09 at 19 16 38](https://cloud.githubusercontent.com/assets/608862/21061392/0ceab478-be44-11e6-920b-1899ad18a8d0.png)

It would be nice if graphiql workspace made variables were equal to `{}` by default or removed  this data node from the request completely when empty.

Cheers!

**Comment by OlegIlyenko** [comment]
Thanks for the report! I recently made a few PRs in GraphiQL which solve these kind of issues:

https://github.com/graphql/graphiql/pull/171/files#diff-2c51ca6a844e000cbc40288fbe06bd28R482

 It is released in v0.8.0. I just need to update GraphiQL version in graphiql-workspace and the issue should be resolved :) I'll do it soon

**Comment by kachkaev** [comment]
Awesome, thanks Oleg! I so much like this extra dimension that you've added to GraphiQL – makes endpoint debugging so much easier!

**Comment by OlegIlyenko** [comment]
Hopefully, it should be fixed with the update to the newest GraphiQL version.
