### ISSUE TITLE
Standalone app & docker image

### ISSUE THREAD

**Issue by kachkaev** [OlegIlyenko/graphiql-workspace#8]
Hi again Oleg,

I found your tool very useful indeed; it even changed how I see GraphiQL in my workflow. Initially, any new GraphQL server I created had `/graphql` and `/graphiql` endpoints, but now I see this an anti-pattern. The main reason is that not every GraphQL server in my team may be written in JS, plus there is also a problem of updating all these copies and carrying lots of identical dependencies around. Using just one GraphiQL tool at a fixed url and saving/loading its state looks much more universal! This reminds me of `redux-devtools`, which once were commonly placed into every new React app but then moved to a Chrome extension.

I made a standalone copy of `graphiql-workspace`, which is basically an instance of `create-react-app` with only one component. The app can be shipped as a pretty lightweight docker container (< 20MB!), which makes it extremely easy to launch at `https://graphiql.yourcompany.com` (this may be viewed as a slightly safer option than running a public copy, plus `cors` in `graphql endpoints` may become more straightforward to setup).

I uploaded the result to GtiLab, here's the URL: https://gitlab.com/kachkaev/graphiql-workspace-app

Feel free to share the link if you want and thanks again for your great work on bringing GraphiQL to a new level!

**Comment by OlegIlyenko** [comment]
This sounds awesome!! I would be great if you can create a PR to update README and include this info (in this repo). I think it would be interesting for many people!

Maybe a "Community" section at the bottom. Then I can also add my graphql-toolbox there as well.
